version: "3"
services:
  sunnycloud:
    build: .
    ports:
      - "8080:8080"
      - "8000:8000"
    environment:
      - DYNAMODB_ENDPOINT
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_REGION
