version: "3"
services:
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
  sunnycloud:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - dynamodb-local
    environment:
      DYNAMODB_ENDPOINT: "http://172.17.0.1:8000"
      AWS_ACCESS_KEY_ID: "asdf"
      AWS_SECRET_ACCESS_KEY: "asefd"
      AWS_REGION: "eu-west-2"

