package com.cornelmarck.sunnycloud.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;

import java.io.Serializable;
import java.util.UUID;

public class UserPrimaryKey implements Serializable {
    private String id;

    public UserPrimaryKey() {}
    public UserPrimaryKey(String userId) {
        setId(userId);
    }

    @DynamoDBHashKey(attributeName = "UserEmailAddress")
    public String getId() {
        return id;
    }
    public void setId(String id) {
        this.id = id;
    }

    @DynamoDBRangeKey(attributeName = "Site_Mode_Timestamp")
    public String getSortKey() {
        return "User";
    }
    public void setSortKey(String sortKey) {
    }
}
