package com.cornelmarck.sunnycloud.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import org.springframework.data.annotation.Id;

import java.io.Serializable;
import java.util.UUID;

@DynamoDBTable(tableName="Main")
public class User {
    @Id
    private PrimaryKey primaryKey;

    private String emailAddress;
    private String mobileNumber;

    public User() {
        this(null, null);
    }

    public User(String emailAddress, String mobileNumber) {
        this.primaryKey = new PrimaryKey();
        this.emailAddress = emailAddress;
        this.mobileNumber = mobileNumber;
    }

    @DynamoDBAutoGeneratedKey
    @DynamoDBHashKey(attributeName = "UserId")
    public UUID getId() {
        return primaryKey.getId();
    }
    public void setId(UUID id) {
        primaryKey.setId(id);
    }

    @DynamoDBRangeKey(attributeName = "SiteModeTimestamp")
    public String getSortKey() {
        return primaryKey.getSortKey();
    }
    public void setSortKey(String sortKey) {
        primaryKey.setSortKey(sortKey);
    }

    @DynamoDBAttribute(attributeName = "EmailAddress")
    public String getEmailAddress() {
        return emailAddress;
    }
    public void setEmailAddress(String emailAddress) {
        this.emailAddress = emailAddress;
    }

    @DynamoDBAttribute(attributeName = "MobileNumber")
    public String getMobileNumber() {
        return mobileNumber;
    }
    public void setMobileNumber(String mobileNumber) {
        this.mobileNumber = mobileNumber;
    }

    public static class PrimaryKey implements Serializable {
        private UUID id;
        private String sortKey;

        public PrimaryKey() {
            sortKey = "User";
        }

        @DynamoDBAutoGeneratedKey
        @DynamoDBHashKey(attributeName = "UserId")
        public UUID getId() {
            return id;
        }
        public void setId(UUID id) {
            this.id = id;
        }

        @DynamoDBRangeKey(attributeName = "SiteModeTimestamp")
        public String getSortKey() {
            return sortKey;
        }
        public void setSortKey(String key) {
            this.sortKey = key;
        }
    }
}
